# Generated by Django 3.1 on 2020-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='myportfolio/pictures/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
