# Generated by Django 3.1 on 2020-08-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='picture',
            field=models.ImageField(upload_to='portfolioo/pictures/'),
        ),
    ]
