# Generated by Django 3.1 on 2020-08-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_auto_20200825_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='personalport',
        ),
    ]
